Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "hubot-dev"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder ".", "/vagrant", type: "rsync" ,rsync_exclude: ["./git", "myhubot/node_modules"]
end
