Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3306, host: 3307

  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provision "shell" do |shell|
    shell.path = "install_mysql.sh"
  end



end
