Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "standalone" do |standalone|
   standalone.vm.hostname = "standalone"
   standalone.vm.network "forwarded_port", host: 27018, guest: 27018, id: "mongodb"
   standalone.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "standalone.pp"      
    end
   end
  end 